#if !canImport(ObjectiveC)
import XCTest

extension SE0288_IsPowerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SE0288_IsPowerTests = [
        ("testDemo", testDemo),
        ("testDifferentBaseTypes", testDifferentBaseTypes),
        ("testIntegerTypes", testIntegerTypes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SE0288_IsPowerTests.__allTests__SE0288_IsPowerTests),
    ]
}
#endif
